import Section from 'molecules/Section/Section';

import Footer from 'components/Footer/Footer';

import type { ComponentStory } from '@storybook/react';

const Template: ComponentStory<typeof Footer> = args => (
  <Section id="footer-section" backgroundColor="Black">
    <Footer {...args} />
  </Section>
);
export const footer = Template.bind({});
footer.parameters = {
  controls: {
    include: ['hasFooter'],
  },
};
footer.args = {
  id: '105656969',
  __typename: 'ComponentFooterRecord',
  internalName: 'Global Footer',
  heading: 'Get news and product updates.',
  subhead: 'I’m good with the [Privacy Policy](https://deepgram.com/privacy/).',
  menuItem: [
    {
      menuItem: [
        {
          id: '105656112',
          __typename: 'MenuItemRecord',
          internalName: 'Product Overview',
          heading: 'Product Overview',
          url: 'https://deepgram.com/product-overview/',
        },
        {
          id: '105656128',
          __typename: 'MenuItemRecord',
          internalName: 'Transcription',
          heading: 'Transcription',
          url: 'https://deepgram.com/product/transcription/',
        },
        {
          id: '105656131',
          __typename: 'MenuItemRecord',
          internalName: 'Understanding',
          heading: 'Understanding',
          url: 'https://deepgram.com/product/speech-understanding/',
        },
        {
          id: '105656133',
          __typename: 'MenuItemRecord',
          internalName: 'Model Overview',
          heading: 'Model Overview',
          url: 'https://deepgram.com/product/model-overview/',
        },
        {
          id: '105656143',
          __typename: 'MenuItemRecord',
          internalName: 'Languages',
          heading: 'Languages',
          url: 'https://deepgram.com/product/languages/',
        },
        {
          id: '105656167',
          __typename: 'MenuItemRecord',
          internalName: 'Why Deepgram',
          heading: 'Why Deepgram',
          url: 'https://deepgram.com/why-deepgram/',
        },
        {
          id: '105656187',
          __typename: 'MenuItemRecord',
          internalName: 'Free API Key',
          heading: 'Free API Key',
          url: 'https://console.deepgram.com/signup',
        },
        {
          id: '105656203',
          __typename: 'MenuItemRecord',
          internalName: 'Pricing',
          heading: 'Pricing',
          url: 'https://deepgram.com/pricing/',
        },
      ],
      id: '105656204',
      __typename: 'MenuItemRecord',
      internalName: 'Product Menu',
      heading: 'Product',
      url: 'https://deepgram.com/asr-comparison/compare-accuracy/',
    },
    {
      menuItem: [
        {
          id: '105656209',
          __typename: 'MenuItemRecord',
          internalName: 'Built With Deepgram',
          heading: 'Built With Deepgram',
          url: 'https://deepgram.com/built-with-deepgram/',
        },
        {
          id: '105656212',
          __typename: 'MenuItemRecord',
          internalName: 'Contact Centers',
          heading: 'Contact Centers',
          url: 'https://deepgram.com/solutions/contact-centers/',
        },
        {
          id: '105656214',
          __typename: 'MenuItemRecord',
          internalName: 'Speech Analytics',
          heading: 'Speech Analytics',
          url: 'https://deepgram.com/solutions/speech-analytics/',
        },
        {
          id: '105656229',
          __typename: 'MenuItemRecord',
          internalName: 'Conversational AI',
          heading: 'Conversational AI',
          url: 'https://deepgram.com/deepgram-for-voicebots-and-chatbots/',
        },
        {
          id: '105656244',
          __typename: 'MenuItemRecord',
          internalName: 'Podcast Transcription',
          heading: 'Podcast Transcription',
          url: 'https://deepgram.com/deepgram-for-podcast-transcription/',
        },
      ],
      id: '105656246',
      __typename: 'MenuItemRecord',
      internalName: 'Solutions Menu',
      heading: 'Solutions',
      url: 'https://deepgram.com/asr-comparison/compare-accuracy/#',
    },
    {
      menuItem: [
        {
          id: '105656250',
          __typename: 'MenuItemRecord',
          internalName: 'Documentation',
          heading: 'Documentation',
          url: 'https://developers.deepgram.com/documentation/',
        },
        {
          id: '105656253',
          __typename: 'MenuItemRecord',
          internalName: 'SDK + Tools',
          heading: 'SDK + Tools',
          url: 'https://developers.deepgram.com/sdks-tools/',
        },
        {
          id: '105656255',
          __typename: 'MenuItemRecord',
          internalName: 'Guides',
          heading: 'Guides',
          url: 'https://developers.deepgram.com/documentation/guides/',
        },
        {
          id: '105656256',
          __typename: 'MenuItemRecord',
          internalName: 'Tutorials',
          heading: 'Tutorials',
          url: 'https://blog.deepgram.com/categories/tutorial/',
        },
        {
          id: '105656259',
          __typename: 'MenuItemRecord',
          internalName: 'On-prem Deployment',
          heading: 'On-prem Deployment',
          url: 'https://developers.deepgram.com/on-prem/',
        },
        {
          id: '105656275',
          __typename: 'MenuItemRecord',
          internalName: 'API Reference',
          heading: 'API Reference',
          url: 'https://developers.deepgram.com/api-reference/',
        },
        {
          id: '105656277',
          __typename: 'MenuItemRecord',
          internalName: 'Status',
          heading: 'Status',
          url: 'https://status.deepgram.com/',
        },
        {
          id: '105656279',
          __typename: 'MenuItemRecord',
          internalName: 'Changelog',
          heading: 'Changelog',
          url: 'https://deepgram.com/changelog/',
        },
        {
          id: '105656282',
          __typename: 'MenuItemRecord',
          internalName: 'Support',
          heading: 'Support',
          url: 'https://developers.deepgram.com/support/',
        },
        {
          id: '105656288',
          __typename: 'MenuItemRecord',
          internalName: 'Community Forum',
          heading: 'Community Forum',
          url: 'https://github.com/orgs/deepgram/discussions',
        },
      ],
      id: '105656290',
      __typename: 'MenuItemRecord',
      internalName: 'Docs Menu',
      heading: 'Docs',
      url: '',
    },
    {
      menuItem: [
        {
          id: '105656293',
          __typename: 'MenuItemRecord',
          internalName: 'About',
          heading: 'About',
          url: 'https://deepgram.com/about/',
        },
        {
          id: '105656294',
          __typename: 'MenuItemRecord',
          internalName: 'Article',
          heading: 'Article',
          url: 'https://blog.deepgram.com/',
        },
        {
          id: '105656296',
          __typename: 'MenuItemRecord',
          internalName: 'Newsroom',
          heading: 'Newsroom',
          url: 'https://deepgram.com/company/newsroom/',
        },
        {
          id: '105656298',
          __typename: 'MenuItemRecord',
          internalName: 'Careers',
          heading: 'Careers',
          url: 'https://deepgram.com/company/careers/',
        },
        {
          id: '105656299',
          __typename: 'MenuItemRecord',
          internalName: ' Contact Us',
          heading: ' Contact Us',
          url: 'https://deepgram.com/contact-us',
        },
        {
          id: '105656301',
          __typename: 'MenuItemRecord',
          internalName: 'Security',
          heading: 'Security',
          url: 'https://deepgram.com/data-security/',
        },
      ],
      id: '105656302',
      __typename: 'MenuItemRecord',
      internalName: 'About Menu',
      heading: 'About',
      url: 'https://deepgram.com/about/',
    },
    {
      menuItem: [
        {
          id: '105656310',
          __typename: 'MenuItemRecord',
          internalName: 'ASR Comparison Tool',
          heading: 'ASR Comparison Tool',
          url: 'https://deepgram.com/asr-comparison/',
        },
        {
          id: '105656312',
          __typename: 'MenuItemRecord',
          internalName: 'Speech-to-Text Self Assessment',
          heading: 'Speech-to-Text Self Assessment',
          url: 'https://deepgram.com/speech-to-text-self-assessment/',
        },
        {
          id: '105656319',
          __typename: 'MenuItemRecord',
          internalName: 'OpenAI Whisper Alternative',
          heading: 'OpenAI Whisper Alternative',
          url: 'https://deepgram.com/compare-openai-whisper-alternatives/',
        },
        {
          id: '105656321',
          __typename: 'MenuItemRecord',
          internalName: 'Google STT Alternative',
          heading: 'Google STT Alternative',
          url: 'https://deepgram.com/compare-google-stt-alternatives/',
        },
        {
          id: '105656322',
          __typename: 'MenuItemRecord',
          internalName: 'Amazon Transcribe STT Alternative',
          heading: 'Amazon Transcribe STT Alternative',
          url: 'https://deepgram.com/compare-amazon-transcribe-api-alternatives/',
        },
        {
          id: '105656323',
          __typename: 'MenuItemRecord',
          internalName: 'Microsoft Azure STT Alternative',
          heading: 'Microsoft Azure STT Alternative',
          url: 'https://deepgram.com/compare-microsoft-azure-stt-alternatives/',
        },
        {
          id: '105656324',
          __typename: 'MenuItemRecord',
          internalName: 'Nuance Dragon STT Alternative',
          heading: 'Nuance Dragon STT Alternative',
          url: 'https://deepgram.com/compare-nuance-dragon-speech-recognition-alternatives/',
        },
        {
          id: '105656330',
          __typename: 'MenuItemRecord',
          internalName: 'AssemblyAI STT Alternative',
          heading: 'AssemblyAI STT Alternative',
          url: 'https://deepgram.com/compare-assembly-ai-speech-to-text-api-alternatives/',
        },
        {
          id: '105656338',
          __typename: 'MenuItemRecord',
          internalName: 'Speechmatics STT Alternative',
          heading: 'Speechmatics STT Alternative',
          url: 'https://deepgram.com/compare-speechmatics-speech-to-text-api-alternatives/',
        },
      ],
      id: '105656339',
      __typename: 'MenuItemRecord',
      internalName: 'Compare Menu',
      heading: 'Compare',
      url: 'https://deepgram.com/asr-comparison/compare-accuracy/#',
    },
  ],
  bottomFooter: [
    {
      id: '105656964',
      __typename: 'MenuItemRecord',
      internalName: 'Terms',
      heading: 'Terms',
      url: 'https://deepgram.com/terms/',
    },
    {
      id: '105656968',
      __typename: 'MenuItemRecord',
      internalName: 'Privacy',
      heading: 'Privacy',
      url: 'https://deepgram.com/privacy/',
    },
  ],
  form: {
    id: '105656090',
    __typename: 'ComponentFormRecord',
    internalName: 'Footer Form',
    formId: 'inline_sign_up',
  },
  disclaimerText: 'Copyright © 2023 Deepgram',
} as any;
